package com.a0xffffffff.dinesum;

import android.util.Log;

/**
 * Represents a Request created by a User.
 */
public class Request {

    private static final String TAG = "Request";  // for debugging

    private String mRequestID;  // will be generated by Firebase when adding to database
    private String mRequesterID;  // cannot be modified
    private String mReserverID;  // will be initialized after request is claimed
    private String mRequestState;
    private RequestData mRequestData;

    /**
     * Creates a Request instance.
     * This is the default constructor required for calls to DataSnapshot.getValue(User.class).
     */
    public Request() {

    }

    /**
     * Creates a Request instance.
     * @param requesterID The requester's unique ID.
     * @param requestData Information about the request's time, party, restaurant, and payment.
     */
    public Request(String requesterID, RequestData requestData) {
        // generate unique request ID using Firebase
        mRequesterID = requesterID;
        mRequestState = RequestState.PENDING;
        mRequestData = requestData;
        mReserverID = "";
    }

    /**
     * Creates a Request instance.
     * @param requesterID The requester's unique ID.
     * @param requestData Information about the request's time, party, restaurant, and payment.
     * @param requestID The request's unique ID.
     */
    public Request(String requesterID, RequestData requestData, String requestID) {
        mRequestID = requestID;
        mRequesterID = requesterID;
        mRequestState = RequestState.PENDING;
        mRequestData = requestData;
        mReserverID = "";
    }

    public String getRequestID() {
        return mRequestID;
    }

    public void setRequestID(String requestID) { mRequestID = requestID; }

    public String getRequesterID() {
        return mRequesterID;
    }

    public void setRequesterID(String requesterID) {
        mRequesterID = requesterID;
    }

    public String getReserverID() {
        return mReserverID;
    }

    public void setReserverID(String reserverID) {
        mReserverID = reserverID;
    }

    public String getRequestState() {
        return mRequestState;
    }

    public void setRequestState(String requestState) {
        mRequestState = requestState;
    }

    public RequestData getRequestData() {
        return mRequestData;
    }

    public void setRequestData(RequestData requestData) {
        mRequestData = requestData;
    }

}
